name: loadmore
description: listview scroll to bottom ,can load more data. help developer paging load data.
version: 2.1.0
email: cjl_spy@163.com
homepage: https://github.com/OpenFlutter/flutter_listview_loadmore
publish_to: http://pub.dev

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter